apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-git-jenkins-docker
  labels:
    app: spring-git-jenkins-docker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-git-jenkins-docker
  template:
    metadata:
      labels:
        app: spring-git-jenkins-docker
    spec:
      containers:
        - name: spring-git-jenkins-docker
          image: 7013781152/spring-git-jenkins-docker-image-docker-hub-kubernetes:v1
          ports:
            - containerPort: 8080