apiVersion: v1
kind: Service
metadata:
  name: spring-git-jenkins-service-final
spec:
  type: NodePort
  selector:
    app: spring-git-jenkins-docker-final
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007